services:
  home:
    build: ./home
    environment:
      - CART_ORIGIN=http://cart:3000
    ports:
      - "3000:3000"
    depends_on:
      - cart

  cart:
    build: ./cart
    ports:
      - "3001:3000"
